<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <!-- Windows-specific target framework -->
        <Version>0.0.6</Version>
        <Description></Description>
        <PackageProjectUrl></PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <UseWindowsForms>true</UseWindowsForms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugType>None</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="System.Windows.Forms" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="SimpleCharacterSelectPlugin.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <Content Include="Assets\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="DalamudPackager" Version="15.0.0" />
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
      <PackageReference Include="Penumbra.Api" Version="5.15.1" />
    </ItemGroup>

</Project>
